const PRODUCT_LOADING="PRODUCT_LOADING";
const PRODUCT_SUCCESS="STORE_SUCCESS";
const PRODUCT_ERROR="PRODUCT_ERROR";

const CURRENT_PRODUCT_LOADING="CURRENT_PRODUCT_LOADING";
const CURRENT_PRODUCT_ERROR="CURRENT_PRODUCT_ERROR";
const CURRENT_PRODUCTS_SUCCESS="CURRENT_PRODUCTS_SUCCESS";


export {PRODUCT_LOADING,PRODUCT_SUCCESS,PRODUCT_ERROR,CURRENT_PRODUCT_LOADING,CURRENT_PRODUCT_ERROR,CURRENT_PRODUCTS_SUCCESS}